# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_call:
    inputs:
      SUPABASE_URL:
        type: string
        required: true
      SUPABASE_ANON_KEY:
        type: string
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Adding .env.local file
      run: |
        cat << EOF > .env.local
        NEXT_PUBLIC_SUPABASE_URL=${{ inputs.SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ inputs.SUPABASE_ANON_KEY }}
        SUPABASE_URL=${{ inputs.SUPABASE_URL }}
        SUPABASE_ANON_KEY=${{ inputs.SUPABASE_ANON_KEY }}
        EOF

    - run: |
        if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
        elif [ -f package-lock.json ]; then npm ci; \
        elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
        else echo "Lockfile not found." && exit 1; \
        fi
    - run: yarn build
