# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOMAIN_NAME: oceanwareltd.co.tz

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Adding .env file
        run: |
          cat << EOF > .env.local
          ---
          NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co
          SUPABASE_URL=https://your-project.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key
          SUPABASE_ANON_KEY=your-anon-key
          EOF

      - run: |
          if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
          elif [ -f package-lock.json ]; then npm ci; \
          elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
          else echo "Lockfile not found." && exit 1; \
          fi
      - run: yarn build
